apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-k8s-deployment
  labels:
    app: yolo-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-k8s
  template:
    metadata:
      labels:
        app: yolo-k8s
    spec:
      containers:
      - name: yolo-k8s-backend
        image: warui1225/yolo-backend:latest
        resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
        ports:
            - containerPort: 5050
        env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: MONGO_URI