apiVersion: v1
kind: Service
metadata:
  name: yolo-k8s-backend-service
spec:
  selector:
    app: yolo-k8s
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
      nodePort: 31000
