apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yolo-k8s-statefulset
  labels:
    app: yolo-k8s
spec:
  serviceName: yolo-k8s-service
  replicas: 3
  selector:
    matchLabels:
      app: yolo-k8s
  template:
    metadata:
      labels:
        app: yolo-k8s
    spec:
      containers:
      - name: yolo-k8s-backend
        image: warui1225/yolo-backend:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5050
      - name: yolo-k8s-frontend
        image: warui1225/yolo-frontend:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
