apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: yolo-k8s
    app.kubernetes.io/name: yolo-k8s-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
