apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: yolo-k8s
    app.kubernetes.io/name: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017