apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap
data:
  MONGO_URI: "mongodb+srv://waruikinyuru:5u8ZWvw46xBuG3Vm@nodeepressproject.lhdzplz.mongodb.net/YOLO?retryWrites=true&w=majority"
