apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
data:
  username: bW9uZ291c2Vy
  password: bW9uZ29QYXNz
  MONGO_URI: bW9uZ29kYitzcnY6Ly93YXJ1aWtpbnl1cnU6NXU4Wld2dzQ2eEJ1RzNWbUBub2RlZXByZXNzcHJvamVjdC5saGR6cGx6Lm1vbmdvZGIubmV0L1lPTE8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5

